### ISSUE TITLE
the result is bad

### ISSUE THREAD

**Issue by ForrestPi** [yaoyx689/AMM_NRR#3]
Hi the result is bad without landmarkFile param
![image](https://user-images.githubusercontent.com/12846142/221607307-9fdba594-3c4a-4545-af55-1db61b95d2bd.png)

using
`./AMM_NRR <srcFile> <tarFile> <outPath> <radius> <alpha> <beta>`
the obj file is blew
[obj.zip](https://github.com/yaoyx689/AMM_NRR/files/10841241/obj.zip)

could you help me how to run correctly ?

**Comment by ForrestPi** [comment]
@yaoyx689 could you share some tips how to run the code ?

**Comment by yaoyx689** [comment]
Hello, the reason for this result is that the two input models (flame.obj & ict.obj) have a large translation. It is recommended that you use the rigid registration method (eg. https://github.com/yaoyx689/Fast-Robust-ICP) to align the two model before running this code.

I run the rigid registration and save the result in ``rigid_reg.obj`` and run

``./AMM_NRR ./obj/rigid_reg.obj ./obj/ict.obj ./obj/out 10 5 5``

and obtain the normal result ( [res.zip](https://github.com/yaoyx689/AMM_NRR/files/10887943/res.zip)).  You can also adjust the parameters ``alpha`` and ``beta`` to get better results. 

Since the eyeball is independent of other parts in the model (flame.obj), the lack of regularization constraints may make the results have some strange situations. If you want to fix this you can fix their positions. 


![snapshot00](https://user-images.githubusercontent.com/47818173/222890384-0f9b520d-8e05-42c6-97f7-15f40a9408d0.png)

**Comment by ForrestPi** [comment]
@yaoyx689 thank you so much
